name: build-sphinx-docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Build docs
        id: build
        run: |
          cd docs
          make html
      - name: Upload static files as artifact
        id: deployement
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployement
        uses: actions/deploy-pages@v4
